### ISSUE TITLE
Armazenamento desnecessário

### ISSUE THREAD

**Issue by Claudio-Caron** [IgorSFranca/Portfolio#1]
**Tarde patrão**
Verificando seu código do Jogo da forca, observei uma reserva de armazenamento desnecessária.
<img width="249" alt="Captura de tela 2023-09-08 145811" src="https://github.com/IgorSFranca/Portfolio/assets/140202178/4e0e3bec-000e-4dbb-bb5c-195fc9e73b70">
### possível solução:
Almejando a troca de palavra futuramente, seria interessante usar o comando "#define" para assegurar a manipulação do tamanho, declarando uma constante com valor fixo .No caso, seria interessante deixar com o valor 10(estou testando as Issues tbm).

**Comment by IgorSFranca** [comment]
Bom dia Claudio, tudo bom?

Suas recomendações são válidas e de grande ajuda.
O código foi ajustado.
Obrigado.
